const productData = [
    {
      img: "https://m.media-amazon.com/images/I/41G88ZZHj0L.jpg",
      title: "Nike Polo T-Shirt",
      reviews: "(123 reviews)",
      prevPrice: "$140.00",
      newPrice: "200",
      company: "Nike",
      color: "white",
      category: "PoloT-Shirt",
      size: ["S", "M", "L"],
    },
    {
      img: "https://m.media-amazon.com/images/I/61yMhvFmC4L._SX569_.jpg",
      title: "Nike Air Plus",
      reviews: "(123 reviews)",
      prevPrice: "$140.00",
      newPrice: "150",
      company: "Nike",
      color: "black",
      category: "PoloT-Shirt",
      size: ["M", "L"],
    },
    {
      img: "https://m.media-amazon.com/images/I/71af25JeJ1L._SX569_.jpg",
      title: "Nike Fit Polo Shirt",
      reviews: "(123 reviews)",
      prevPrice: "$140.00",
      newPrice: "180",
      company: "Nike",
      color: "green",
      category: "PoloT-Shirt",
      size: ["S", "XL"],
    },
    {
      img: "https://m.media-amazon.com/images/I/81noqdPnbWL._SX569_.jpg",
      title: "Striped Fit Polo Shirt",
      reviews: "(123 reviews)",
      prevPrice: "$140.00",
      newPrice: "120",
      company: "Adidas",
      color: "grey",
      category: "PoloT-Shirt",
      size: ["M", "L", "XL"],
    },
    {
        img: "https://m.media-amazon.com/images/I/51i8PZCJVBL._SY741_.jpg",
        title: "Flat Slip On Pumps",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "white",
        category: "T-Shirt",
        size: ["S", "M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/61l8cNyTabL._SX569_.jpg",
        title: "Knit Ballet Flat",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "T-Shirt",
        size: ["M", "L"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/51LbLP7NLKL._SY741_.jpg",
        title: "Regular Fit T-Shirt",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans ",
        color: "white",
        category: "T-Shirt",
        size: ["S", "XL"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/51pL2wPAIGL._SY741_.jpg",
        title: "Nike Drop Shoulder",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "oversized",
        size: ["M", "L", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/617UyikiUsL._SY741_.jpg",
        title: "Drop Shoulder Green",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "green",
        category: "oversized",
        size: ["S", "M", "L"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/51YF8Ghmm1L._SY741_.jpg",
        title: "Oversized Fit T-Shirt",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Adidas",
        color: "blue",
        category: "oversized",
        size: ["M", "L"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/51WLLmgyM-L._SX679_.jpg",
        title: "Puma Oversized T-Shirt",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "green",
        category: "oversized",
        size: ["S", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/51Sg-5JSOdL._SX679_.jpg",
        title: "Unisex's Oversized",
        reviews: "(123 reviews)",
        prevPrice: "$145,00",
        newPrice: "150",
        company: "Puma",
        color: "red",
        category: "oversized",
        size: ["M", "L", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/51nImubQX4L._SX679_.jpg",
        title: "Men's Oversized",
        reviews: "(123 reviews)",
        prevPrice: "$150,00",
        newPrice: "150",
        company: "Puma",
        color: "black",
        category: "oversized",
        size: ["S", "M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/515RdZ6Y65L._SX679_.jpg",
        title: "Regular Polyester",
        reviews: "(123 reviews)",
        prevPrice: "$130,00",
        newPrice: "120",
        company: "Puma",
        color: "white",
        category: "oversized",
        size: ["M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/51aqRpDtLvL._SY741_.jpg",
        title: "Solid Classic Fit",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Puma",
        color: "black",
        category: "oversized",
        size: ["S", "XL"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/51dW7v4Up6L._SX679_.jpg",
        title: "Puma Men's T-Shirt",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Puma",
        color: "green",
        category: "oversized",
        size: ["M", "L", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/518v6ZWbv7L._SY741_.jpg",
        title: "Polo Regular Fit",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "red",
        category: "PoloT-Shirt",
        size: ["S", "M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/61n-5PCGEzL._SX569_.jpg",
        title: "Van Heusen Ultra Soft",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "white",
        category: "V-Neck",
        size: ["M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/61+DzCB0aKL._SY741_.jpg",
        title: "Van Heusen Acrylic Blend",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Vans",
        color: "blue",
        category: "V-Neck",
        size: ["S", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/61RjTkZoZvL._SX569_.jpg",
        title: "Half Sleeve Crew Neck",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Nike",
        color: "black",
        category: "V-Neck",
        size: ["M", "L", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/71zFHE+h09L._SX679_.jpg",
        title: "Round Neck Sleeveless",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Vans",
        color: "black",
        category: "Sleeveless",
        size: ["S", "M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/51+CUDeGvmL._SX679_.jpg",
        title: "Puma Men's Sleeveless ",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "100",
        company: "Puma",
        color: "black",
        category: "Sleeveless",
        size: ["M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/71sDF-fLRVL._SX679_.jpg",
        title: "Nike Men's Sleeveless",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Nike",
        color: "red",
        category: "Sleeveless",
        size: ["S", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/61XjCM+sA2L._SY741_.jpg",
        title: "Nike Printed Oversized",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "red",
        category: "oversized",
        size: ["M", "L", "XL"],
      },
    
      {
        img: "https://m.media-amazon.com/images/I/71YNmEgjqXL._SY741_.jpg",
        title: "Nike Men's Solid",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "200",
        company: "Nike",
        color: "black",
        category: "Sleeveless",
        size: ["S", "M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/715Yg5C7ySL._SX569_.jpg",
        title: "Adidas Men's Solid",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "Sleeveless",
        size: ["M", "L"],
      },
      {
        img: "https://m.media-amazon.com/images/I/71YtKuqO3kL._SX569_.jpg",
        title: "Amore Fashion Stilettos",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "150",
        company: "Adidas",
        color: "white",
        category: "Sleeveless",
        size: ["S", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/41bDFPu9KML._SX679_.jpg",
        title: "Adidas Men's Fitted ",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "Sleeveless",
        size: ["M", "L", "XL"],
      },
      {
        img: "https://m.media-amazon.com/images/I/717Mn2CCfQL._SX569_.jpg",
        title: "Adidas Men's Regular Fit",
        reviews: "(123 reviews)",
        prevPrice: "$140,00",
        newPrice: "50",
        company: "Adidas",
        color: "black",
        category: "T-Shirt",
        size: ["S", "M", "L"],
      },
  ];
  
  export default productData;
  